version: 2.1

workflows:
  test:
    jobs:
      - build-run-linux:
          context: hello-world-demos

  test-daily:
    triggers:
    - schedule:
        cron: "0 6 * * *"
        filters:
          branches:
            only: main
    jobs:
    - build-run-linux:
        context: hello-world-demos

# This CI build ensures that the demo both compiles and works correctly. For the runtime test,
# we use an SDK key and flag key that are passed in via the CircleCI project configuration;
# the flag is configured to return a true value.

jobs:
  build-run-linux:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install poetry
          command: apt-get update && apt-get install -y python3-poetry

      - run:
          name: Install dependencies
          command: poetry install

      - run:
          name: Run hello
          command: |
            export LAUNCHDARKLY_SERVER_SDK="${LD_HELLO_WORLD_SDK_KEY}"
            export LAUNCHDARKLY_FLAG_KEY="${LD_HELLO_WORLD_FLAG_KEY_WITH_TRUE_VALUE}"
            poetry run python main.py | tee output.txt

      - run:
          name: Check output
          command: |
            grep "is True for this context" output.txt || (echo "Flag did not evaluate to expected true value" && exit 1)
