name: Build and run
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed if using OIDC to get release secrets.

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install

      - uses: launchdarkly/gh-actions/actions/verify-hello-app@verify-hello-app-v2.0.0
        with:
          use_server_key: true
          role_arn: ${{ vars.AWS_ROLE_ARN }}
          command: poetry run python main.py
